language: cpp

compiler:
 - gcc

install:
 - sudo apt-get install -y libgtest-dev
 - "cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib/; cd -"
 - sudo pip install cpp-coveralls